name: Build/Release

on:
  create:
    tags:
      - v*

  workflow_dispatch:

jobs:
  release:
    name: Build/Release Electron Application
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # todo: linux/macos build
        os: [windows-latest]
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/electron
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install
      - name: Compile Typescript
        run: yarn build
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Platform
        id: platform
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ runner.os }}
      - name: Set Version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Build/Release Electron Application
        run: yarn run electron-builder --${{ steps.platform.outputs.lowercase }} --publish always -c.releaseInfo.releaseNotes="${{ steps.changelog.outputs.changelog }}"s
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_PRE_RELEASE: ${{ startsWith( $RELEASE_VERSION, v0 ) }}
