name: Release

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Build/Release Treecord Electron application
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/electron
      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v2-beta
      - name: Build/Release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # todo: automated release notes along with
          # actually releasing the build instead of drafting it
          # args: -c.releaseInfo.releaseNotes="release notes here"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
