name: Build/Release

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Build/Release Electron application
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # todo: linux/macos build
        os: [windows-latest]
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/electron
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build/Release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # todo: automated release notes along with
          # actually releasing the build instead of drafting it
          # args: -c.releaseInfo.releaseNotes="release notes here"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
