name: Build/Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Build/Release Electron Application
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # todo: linux/macos build
        os: [windows-latest]
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/electron
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install
      - name: Compile Typescript
        run: yarn build
      - name: Get Platform
        id: platform
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ runner.os }}
      - name: Get Version
        id: version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Build/Release Electron Application
        run: yarn run electron-builder --${{ steps.platform.outputs.lowercase }} --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_PRE_RELEASE: ${{ startsWith( steps.version.outputs.current-version, 0 ) }}
